apiVersion: apps/v1
kind: Deployment

metadata:
  name: vulnerable-nginx

spec:
  replicas: 1

  selector:
    matchLabels:
      app: vulnerable-nginx

  template:
    metadata:
      labels:
        app: vulnerable-nginx

    spec:
      containers:
      - name: nginx
        image: nginx:1.21.6

        securityContext:
          privileged: false
          runAsUser: 10001
          runAsGroup: 10001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]

        ports:
        - containerPort: 80